package com.boxin.beautypine.model;

/**
 * 直播model
 * User: zouyu
 * Date: :2017/10/9
 * Version: 1.0
 */


public class ProgramLive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.t_id
     *
     * @mbggenerated
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.start_time
     *
     * @mbggenerated
     */
    private Integer startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.end_time
     *
     * @mbggenerated
     */
    private Integer endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.keyword
     *
     * @mbggenerated
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.init_img
     *
     * @mbggenerated
     */
    private String initImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.live_url
     *
     * @mbggenerated
     */
    private String liveUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.play_back_url
     *
     * @mbggenerated
     */
    private String playBackUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.flv_url
     *
     * @mbggenerated
     */
    private String flvUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.m3u8_url
     *
     * @mbggenerated
     */
    private String m3u8Url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.rtmp_url
     *
     * @mbggenerated
     */
    private String rtmpUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.stream_name
     *
     * @mbggenerated
     */
    private String streamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.oss_object
     *
     * @mbggenerated
     */
    private String ossObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.cut_img
     *
     * @mbggenerated
     */
    private String cutImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.share_times
     *
     * @mbggenerated
     */
    private Integer shareTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.play_times
     *
     * @mbggenerated
     */
    private Integer playTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.mts_state
     *
     * @mbggenerated
     */
    private Integer mtsState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.onoff
     *
     * @mbggenerated
     */
    private Integer onoff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_program_live.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.id
     *
     * @return the value of bp_program_live.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.id
     *
     * @param id the value for bp_program_live.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.name
     *
     * @return the value of bp_program_live.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.name
     *
     * @param name the value for bp_program_live.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.t_id
     *
     * @return the value of bp_program_live.t_id
     *
     * @mbggenerated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.t_id
     *
     * @param tId the value for bp_program_live.t_id
     *
     * @mbggenerated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.start_time
     *
     * @return the value of bp_program_live.start_time
     *
     * @mbggenerated
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.start_time
     *
     * @param startTime the value for bp_program_live.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.end_time
     *
     * @return the value of bp_program_live.end_time
     *
     * @mbggenerated
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.end_time
     *
     * @param endTime the value for bp_program_live.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.keyword
     *
     * @return the value of bp_program_live.keyword
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.keyword
     *
     * @param keyword the value for bp_program_live.keyword
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.summary
     *
     * @return the value of bp_program_live.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.summary
     *
     * @param summary the value for bp_program_live.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.init_img
     *
     * @return the value of bp_program_live.init_img
     *
     * @mbggenerated
     */
    public String getInitImg() {
        return initImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.init_img
     *
     * @param initImg the value for bp_program_live.init_img
     *
     * @mbggenerated
     */
    public void setInitImg(String initImg) {
        this.initImg = initImg == null ? null : initImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.live_url
     *
     * @return the value of bp_program_live.live_url
     *
     * @mbggenerated
     */
    public String getLiveUrl() {
        return liveUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.live_url
     *
     * @param liveUrl the value for bp_program_live.live_url
     *
     * @mbggenerated
     */
    public void setLiveUrl(String liveUrl) {
        this.liveUrl = liveUrl == null ? null : liveUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.play_back_url
     *
     * @return the value of bp_program_live.play_back_url
     *
     * @mbggenerated
     */
    public String getPlayBackUrl() {
        return playBackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.play_back_url
     *
     * @param playBackUrl the value for bp_program_live.play_back_url
     *
     * @mbggenerated
     */
    public void setPlayBackUrl(String playBackUrl) {
        this.playBackUrl = playBackUrl == null ? null : playBackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.flv_url
     *
     * @return the value of bp_program_live.flv_url
     *
     * @mbggenerated
     */
    public String getFlvUrl() {
        return flvUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.flv_url
     *
     * @param flvUrl the value for bp_program_live.flv_url
     *
     * @mbggenerated
     */
    public void setFlvUrl(String flvUrl) {
        this.flvUrl = flvUrl == null ? null : flvUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.m3u8_url
     *
     * @return the value of bp_program_live.m3u8_url
     *
     * @mbggenerated
     */
    public String getM3u8Url() {
        return m3u8Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.m3u8_url
     *
     * @param m3u8Url the value for bp_program_live.m3u8_url
     *
     * @mbggenerated
     */
    public void setM3u8Url(String m3u8Url) {
        this.m3u8Url = m3u8Url == null ? null : m3u8Url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.rtmp_url
     *
     * @return the value of bp_program_live.rtmp_url
     *
     * @mbggenerated
     */
    public String getRtmpUrl() {
        return rtmpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.rtmp_url
     *
     * @param rtmpUrl the value for bp_program_live.rtmp_url
     *
     * @mbggenerated
     */
    public void setRtmpUrl(String rtmpUrl) {
        this.rtmpUrl = rtmpUrl == null ? null : rtmpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.stream_name
     *
     * @return the value of bp_program_live.stream_name
     *
     * @mbggenerated
     */
    public String getStreamName() {
        return streamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.stream_name
     *
     * @param streamName the value for bp_program_live.stream_name
     *
     * @mbggenerated
     */
    public void setStreamName(String streamName) {
        this.streamName = streamName == null ? null : streamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.oss_object
     *
     * @return the value of bp_program_live.oss_object
     *
     * @mbggenerated
     */
    public String getOssObject() {
        return ossObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.oss_object
     *
     * @param ossObject the value for bp_program_live.oss_object
     *
     * @mbggenerated
     */
    public void setOssObject(String ossObject) {
        this.ossObject = ossObject == null ? null : ossObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.cut_img
     *
     * @return the value of bp_program_live.cut_img
     *
     * @mbggenerated
     */
    public String getCutImg() {
        return cutImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.cut_img
     *
     * @param cutImg the value for bp_program_live.cut_img
     *
     * @mbggenerated
     */
    public void setCutImg(String cutImg) {
        this.cutImg = cutImg == null ? null : cutImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.share_times
     *
     * @return the value of bp_program_live.share_times
     *
     * @mbggenerated
     */
    public Integer getShareTimes() {
        return shareTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.share_times
     *
     * @param shareTimes the value for bp_program_live.share_times
     *
     * @mbggenerated
     */
    public void setShareTimes(Integer shareTimes) {
        this.shareTimes = shareTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.play_times
     *
     * @return the value of bp_program_live.play_times
     *
     * @mbggenerated
     */
    public Integer getPlayTimes() {
        return playTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.play_times
     *
     * @param playTimes the value for bp_program_live.play_times
     *
     * @mbggenerated
     */
    public void setPlayTimes(Integer playTimes) {
        this.playTimes = playTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.mts_state
     *
     * @return the value of bp_program_live.mts_state
     *
     * @mbggenerated
     */
    public Integer getMtsState() {
        return mtsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.mts_state
     *
     * @param mtsState the value for bp_program_live.mts_state
     *
     * @mbggenerated
     */
    public void setMtsState(Integer mtsState) {
        this.mtsState = mtsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.onoff
     *
     * @return the value of bp_program_live.onoff
     *
     * @mbggenerated
     */
    public Integer getOnoff() {
        return onoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.onoff
     *
     * @param onoff the value for bp_program_live.onoff
     *
     * @mbggenerated
     */
    public void setOnoff(Integer onoff) {
        this.onoff = onoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_program_live.del_flag
     *
     * @return the value of bp_program_live.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_program_live.del_flag
     *
     * @param delFlag the value for bp_program_live.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * the field  was connected to tid field
     * called teacher name
     */
    private String teacherName;

    public String getTeacherName() {
        return teacherName;
    }

    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }
}