package com.boxin.beautypine.model;

/**
 * 战记回顾model
 * User: zouyu
 * Date: :2017/10/10
 * Version: 1.0
 */

public class Review {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_page_review.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_page_review.review_url
     *
     * @mbggenerated
     */
    private String reviewUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_page_review.sort_number
     *
     * @mbggenerated
     */
    private Integer sortNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_page_review.review_link
     *
     * @mbggenerated
     */
    private String reviewLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_page_review.onoff
     *
     * @mbggenerated
     */
    private Integer onoff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_page_review.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_page_review.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_page_review.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_page_review.del_flag
     *
     * @mbggenerated
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_page_review.id
     *
     * @return the value of bp_page_review.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_page_review.id
     *
     * @param id the value for bp_page_review.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_page_review.review_url
     *
     * @return the value of bp_page_review.review_url
     *
     * @mbggenerated
     */
    public String getReviewUrl() {
        return reviewUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_page_review.review_url
     *
     * @param reviewUrl the value for bp_page_review.review_url
     *
     * @mbggenerated
     */
    public void setReviewUrl(String reviewUrl) {
        this.reviewUrl = reviewUrl == null ? null : reviewUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_page_review.sort_number
     *
     * @return the value of bp_page_review.sort_number
     *
     * @mbggenerated
     */
    public Integer getSortNumber() {
        return sortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_page_review.sort_number
     *
     * @param sortNumber the value for bp_page_review.sort_number
     *
     * @mbggenerated
     */
    public void setSortNumber(Integer sortNumber) {
        this.sortNumber = sortNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_page_review.review_link
     *
     * @return the value of bp_page_review.review_link
     *
     * @mbggenerated
     */
    public String getReviewLink() {
        return reviewLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_page_review.review_link
     *
     * @param reviewLink the value for bp_page_review.review_link
     *
     * @mbggenerated
     */
    public void setReviewLink(String reviewLink) {
        this.reviewLink = reviewLink == null ? null : reviewLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_page_review.onoff
     *
     * @return the value of bp_page_review.onoff
     *
     * @mbggenerated
     */
    public Integer getOnoff() {
        return onoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_page_review.onoff
     *
     * @param onoff the value for bp_page_review.onoff
     *
     * @mbggenerated
     */
    public void setOnoff(Integer onoff) {
        this.onoff = onoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_page_review.description
     *
     * @return the value of bp_page_review.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_page_review.description
     *
     * @param description the value for bp_page_review.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_page_review.create_time
     *
     * @return the value of bp_page_review.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_page_review.create_time
     *
     * @param createTime the value for bp_page_review.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_page_review.update_time
     *
     * @return the value of bp_page_review.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_page_review.update_time
     *
     * @param updateTime the value for bp_page_review.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_page_review.del_flag
     *
     * @return the value of bp_page_review.del_flag
     *
     * @mbggenerated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_page_review.del_flag
     *
     * @param delFlag the value for bp_page_review.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}
